sudo: required
services: docker

env:
  global:
    - secure: "frcMX7soHy8lim2PzG/WAXkKCrKZdlDcfz3hxodd3JthNx0i9SAywtX0gTTdyiKLHUqA8vLo4vbd9XxdmMteMA/y36mB1H4b0kIFfznRSZpDjfZ4PlgxurXrqXdMHnuufDrQ5UgIu+nIO5o0nrSFuu8Ug+A2v2/yDhv/UrrG79CG2EZni2NwhLB3sB7Nz0+XNw5+dZ/U8xlWchdXLKuC+Q6wWBQ9xZlRBsDXSu+z/kp3LOlU07Xs6rlzuP8nmUJFVTLzK4gBRV6SQFiXpQjC1CVSAOlXKDb17X1BNVe1BaFJ+tYstuGWu+eIuLeY7nIKoBgB0xKnNn/dmnvwyZkKwaAPZ8NN64foiKd+IHcz259+vqcfeVSkvCZgiSMaVE2ITSO5v0Dr18mvl+4JqRkBHQN7chJaMs0Cb9VCi/Ji73wAF6WelQrbIedshJQxg/mdjmDERwVz7lGc1m0Dg8p44KGKR6vyUGFsv53Wmb/MCBImirN0pWU+tUB/rGis5M1qSs0jdzPQAC46I9xB9qsQQQ7WVcdNj+ouoejvnXnREl6cjWvdFbU1FHBt8cVGr85wzuJGlA5Dp2LGeFV8buqRcdmBdLCdURVX5StSFDR5/H5KTZIY1IG0xwRT8lOAbNC9w6EnpshPrHsbgDVS7XozrwEWEKC7q8Ao8bLMB5TFERI="
    - secure: "AnHNBApaEKrN4QXgfMTLsirplxDQMTtErHg3OLlvgEKIP39ZcXd0iooHe9lw2hjXEVgPvGRi2nhCV34+sZf0v8Pnp4UlCS6e+Qs5YsvtxJXTnlD+1U21gvTvpvw09z3DvxWEXMFlRnVF7kUdN/rG5kvoMv6ODP7BcBviT67qtUSkzQFi+9CIncY80Y57DsOmqmPsLBUEIeIktwJhMIyioHSFjgoog6lhotBm34SvvC5pldg/dKIeFA/hU65mWDVwBfToNJFk7LQwzHO6QIXKc5UdhIOiciaGzImJNGWCoGw53Mch9mTuzJoOwWG4uEhcFL+iMoVX6yV7fW9SCwfYPgz/XMUdB+993iC1c/f0jJw6tBo4MOScEbJQt8cfjihmWe+ncs0uaqx+uLugiRLsU5Pa1/JEehdvhLlYQFF0MwubymN7i8u1GIB8G0Xw/XRLMwpBbVHSQnuzV91+7VKox9h5pEVJO+Y1PN/JgQ4aL2j30fT0DJJGvn5O3ihhki8aJorgeAxmmgx6KJZNf9NRVxheWK+gUxYzrBUISN49K9Q2KZSTTdWT7Fxkbi7C/GpLg5caD+c9RuHaESJPVQm0DUrJWmnKho4NtXyFrwCMESUGmSIDH01PdK4FGS55kRhooA5KEqe4khaBkW7kCVpAD9l7HwprnBBHPSlAndDWLqc="

script:
  # Test
  - scripts/xmllint.sh .travis/xmllint
  - scripts/phplint.sh .travis/phplint

  # Test defaults
  - export XMLLINT_DEFAULT_DIR=".travis/xmllint" && scripts/xmllint.sh
  - export PHPLINT_DEFAULT_DIR=".travis/phplint" && scripts/phplint.sh

  # Build image
  - docker build -t ambimax/phptools .

after_script:
  # show all docker images
  - docker images

before_deploy:
  # Login to docker hub
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin

deploy:
  provider: script
  script: docker push ambimax/phptools
  on:
    branch: master
