sudo: required
services: docker

env:
  global:
    - secure: "frcMX7soHy8lim2PzG/WAXkKCrKZdlDcfz3hxodd3JthNx0i9SAywtX0gTTdyiKLHUqA8vLo4vbd9XxdmMteMA/y36mB1H4b0kIFfznRSZpDjfZ4PlgxurXrqXdMHnuufDrQ5UgIu+nIO5o0nrSFuu8Ug+A2v2/yDhv/UrrG79CG2EZni2NwhLB3sB7Nz0+XNw5+dZ/U8xlWchdXLKuC+Q6wWBQ9xZlRBsDXSu+z/kp3LOlU07Xs6rlzuP8nmUJFVTLzK4gBRV6SQFiXpQjC1CVSAOlXKDb17X1BNVe1BaFJ+tYstuGWu+eIuLeY7nIKoBgB0xKnNn/dmnvwyZkKwaAPZ8NN64foiKd+IHcz259+vqcfeVSkvCZgiSMaVE2ITSO5v0Dr18mvl+4JqRkBHQN7chJaMs0Cb9VCi/Ji73wAF6WelQrbIedshJQxg/mdjmDERwVz7lGc1m0Dg8p44KGKR6vyUGFsv53Wmb/MCBImirN0pWU+tUB/rGis5M1qSs0jdzPQAC46I9xB9qsQQQ7WVcdNj+ouoejvnXnREl6cjWvdFbU1FHBt8cVGr85wzuJGlA5Dp2LGeFV8buqRcdmBdLCdURVX5StSFDR5/H5KTZIY1IG0xwRT8lOAbNC9w6EnpshPrHsbgDVS7XozrwEWEKC7q8Ao8bLMB5TFERI="
    - secure: "gstm4Yqjr1zCvRYiHSdtoUtqRk7XWWrnDaZ7wICaDqKDJ4y/QHRDCr7uly6zUCWKuV2dttKqk8nIcl7KpFOukuaBWmB7B9oazOPN1xDxQGFtG7p2F7OfdeRoTMk0lRT/RICKI1IbkdBubm7nnK7YrKmELD3IIg7erj7i1z0+LBvkuZUEs54fGbBjIMwP4o1ZyM3XlwoNbWev92qKPALqVjxWbToV8Y7Ag1/tw0zWPnabzlhc6gysCpC0KdZYiKS0CzEyduC37nzMEGBZ0jQgMZOL6Ctv5/bElvFgWReTof5UJoDmzHCdGNWrJmsYsaYO2bToNDdJbRp0ML+1PjT5dfA5JrCj3rbbTuxd3pZYkJUHnFQMCDADH5pyupdpTxYlifCjsESRk+hAfyLYzDBHfaAaXTyd3e0nNMc6NC99xU9rLBZPVUAbXD+eBN3iOImsQpCp4GAh3Xymaob5/gG4I2pza35lrzf45rjfb+65hv2wHC/m/yGZxEkga4LMqF4IT248xTG2rEX3eJs6VjwftFS0/ItMK7yyw5JV3/zuHmUMR+5w1qmxirSy24DTXevfGCsjSNYzCGLsHKg6meV36llZQZcikDFbPaucbTy2m1bYYv6Ep0G32P0hOtEXoVx3eldfPSP8e+cosw6LpRLZHZpSL2mrcme5ywfNhnka4gg="

script:
  # Test
  - scripts/xmllint.sh .travis/xmllint
  - scripts/phplint.sh .travis/phplint

  # Test defaults
  - export XMLLINT_DEFAULT_DIR=".travis/xmllint" && scripts/xmllint.sh
  - export PHPLINT_DEFAULT_DIR=".travis/phplint" && scripts/phplint.sh

  # Build image
  - docker build -t ambimax/phptools .

after_script:
  # show all docker images
  - docker images

before_deploy:
  # Login to docker hub
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin

deploy:
  provider: script
  script: docker push ambimax/phptools
  on:
    branch: master
