sudo: required
services: docker

env:
  global:
    - secure: "PfAFZUogcQKYtNJ/CXSYGdq40KVlyjQTjsFU/wBHoLTY4UIeFgGOCh0r0xt0cF0NBpJYYKfMMAq2R2nImgjKENr2S68wmc1u9/qyDqWGfnNbMzcQ2GFG86pFT9tOAy//ZW1o0n5pG8p194zS8+CkDiXrPR8RSk9ofehGbx6RlFQ9NLrry3DXBI92HFvug/jGep8IqgUG1PIXFwgK/sCszFx2UXSLRYVWFzTLxuDRRYJZN8k63+9w36Wy56eSApaIcgTEG9hrlfSCjbsEMHNIH4ovLtTzDD9DzOFmSo2tuCFIL3DW3D5CD81FpE+jrX/W9CyKn7pKi/rvM+SRWEWvRUMhQnBn8xYV4p0ztrxDqQOhus2augTe7Ig9J3kgul8ugayNBJEkapKjym5Qe/vEu62mf9LmrJfQN0x2G7wTUkrbgSl7ji1UInsn1t0QJh4oPCr1tIHnHkVfLUl0CyMd0iTXRmmlaScveUB8XauWdnLgaf1pRQoIXv64EshC83ptY4W2R7gvy2rjU6QNfzFMkRK8euDxCFCnvY/c09o1D3yYRwcIPq8nnoyxJ4hBX4/TjavitVc7IkzK2CHKTOY8/jkd31yRpxpw+Jyvymg7gN+G+jQ6uu7kJ0D4c5g/9MdtCehuZybvsdbEGmoIxd2uGCf6ap0sG5EAdWldzJe31jU="
    - secure: "WO8zyQzCnAheCnCmhj4/Bg9XqG+Bdx+n1nkrkStD8KP2T+ox2hoDMgnAJUc2XdxgtoMEMTmvmVvDq1A2D60jqotJAoed7J7iT2SnmECIxEQXJhf2icyPboymeOH9x64zbp0iiqw6sK9iiu0IDhGqx36VRf0+XHwq5iJitseP7oZdqaoemTPdXSH8lwCPTnyz9TN0GnmeXaG0qZwLy69GvB6MErEoY9m2ev16ILSNA5kiXugVNfwJMEgaDPvaEWfJGBvarW+f0G9wWdNZa86n2ppAv1wZRZALIdcUGxt0vYbRFt1TboYBkTqyRYi/pPiJNcrsPvuF/JDO+r0GquDNN7Po0qaDTqGgd2awCicIJxpQgb9MG3RWP74jXt9K2OGWcS+IOC8H9GbVlm50ftUKlsmCCRKRp0a2adHCPUUicthcIqez2QDqAc39IKrYdynmBFsu2aqPomTN54/6lgtqZNQPFGII1yoPsDyfoEe0zDs0IS/XzSGIyhC7T9VMtr0/cSHlq6WmwyMerfk6ETyCPWa0yen7d2CtCyZfp2Nbl86fdyzi/RFQC8ROe9yMsIEzwQ03w2OMhN9W5RxK9uAMNdFF3LvRSKYmEAa3t8JYMom3QTcNuJcolXayei5R5CO4Ep46xXI7WP5npp+q1XSTNDzREhD/W4Dj5J1HoYY/oZM="

script:
  # Build image
  - docker build -t ambimax/phptools .

after_script:
  # show all docker images
  - docker images

before_deploy:
  # Login to docker hub
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"

deploy:
  provider: script
  script: docker push ambimax/phptools
  on:
    branch: master
