on:
  push:
  schedule:
    # Update docker images at 04:25 on Mondays
    - cron: "05 4 * * 1"

jobs:
  dockerfile-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test scripts
        run: make local-tests

      - name: Build image
        run: make build

      - name: Test docker image
        run: make docker-tests

      - name: Display all docker images
        if: ${{ always() }}
        run: docker images

      - name: Login to Docker Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          # We push to the default registry currently. If you want to push to a different registry,
          # uncomment the line below.
          # login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: make push
